[settings]
python_compile = true
go_set_goroot = true
idiomatic_version_file_enable_tools = []
[tools]
usage = "latest"
nodejs = "latest"
golang = "1.20.5"
rust = "1.74.0"
java = "openjdk-21"
ruby = "3.1.3"
yarn = "1.22.5"
python = "3.12.0"
bazel = "5.3.2"
